// <auto-generated />
using System;
using AjoCoreBackend.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AjoCoreBackend.Persistence.Migrations
{
    [DbContext(typeof(AjoCoreDbContext))]
    [Migration("20260624205345_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AjoCoreBackend.Domain.Entities.ContributionLedger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombaWebhookRequestId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SavingCycleMemberId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NombaWebhookRequestId")
                        .IsUnique();

                    b.HasIndex("SavingCycleMemberId");

                    b.ToTable("ContributionLedgers");
                });

            modelBuilder.Entity("AjoCoreBackend.Domain.Entities.NombaVirtualAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("BankName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubAccountId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("NombaVirtualAccounts");
                });

            modelBuilder.Entity("AjoCoreBackend.Domain.Entities.PayoutLedger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MerchantTxRef")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("PayoutDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SavingCycleMemberId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MerchantTxRef")
                        .IsUnique();

                    b.HasIndex("SavingCycleMemberId");

                    b.ToTable("PayoutLedgers");
                });

            modelBuilder.Entity("AjoCoreBackend.Domain.Entities.SavingCycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ContributionAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CycleType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IntervalDays")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NombaSubAccountId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("SavingCycles");
                });

            modelBuilder.Entity("AjoCoreBackend.Domain.Entities.SavingCycleMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("NombaVirtualAccountId")
                        .HasColumnType("uuid");

                    b.Property<int>("PayoutOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("SavingCycleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NombaVirtualAccountId")
                        .IsUnique();

                    b.HasIndex("SavingCycleId", "PayoutOrder")
                        .IsUnique();

                    b.ToTable("SavingCycleMembers");
                });

            modelBuilder.Entity("AjoCoreBackend.Domain.Entities.ContributionLedger", b =>
                {
                    b.HasOne("AjoCoreBackend.Domain.Entities.SavingCycleMember", "Member")
                        .WithMany("Contributions")
                        .HasForeignKey("SavingCycleMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("AjoCoreBackend.Domain.Entities.PayoutLedger", b =>
                {
                    b.HasOne("AjoCoreBackend.Domain.Entities.SavingCycleMember", "Member")
                        .WithMany("Payouts")
                        .HasForeignKey("SavingCycleMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("AjoCoreBackend.Domain.Entities.SavingCycleMember", b =>
                {
                    b.HasOne("AjoCoreBackend.Domain.Entities.NombaVirtualAccount", "VirtualAccount")
                        .WithOne("Member")
                        .HasForeignKey("AjoCoreBackend.Domain.Entities.SavingCycleMember", "NombaVirtualAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AjoCoreBackend.Domain.Entities.SavingCycle", "Cycle")
                        .WithMany("Members")
                        .HasForeignKey("SavingCycleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cycle");

                    b.Navigation("VirtualAccount");
                });

            modelBuilder.Entity("AjoCoreBackend.Domain.Entities.NombaVirtualAccount", b =>
                {
                    b.Navigation("Member");
                });

            modelBuilder.Entity("AjoCoreBackend.Domain.Entities.SavingCycle", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("AjoCoreBackend.Domain.Entities.SavingCycleMember", b =>
                {
                    b.Navigation("Contributions");

                    b.Navigation("Payouts");
                });
#pragma warning restore 612, 618
        }
    }
}
