// <auto-generated />
using System;
using AjoCoreBackend.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AjoCoreBackend.Persistence.Migrations
{
    [DbContext(typeof(AjoCoreDbContext))]
    [Migration("20260701150735_AddReversalLedgerTable")]
    partial class AddReversalLedgerTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AjoCoreBackend.Domain.Entities.ContributionLedger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombaWebhookRequestId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SavingCycleMemberId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NombaWebhookRequestId")
                        .IsUnique();

                    b.HasIndex("SavingCycleMemberId");

                    b.ToTable("ContributionLedgers");
                });

            modelBuilder.Entity("AjoCoreBackend.Domain.Entities.CooperativeAdmin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResetPasswordToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResetPasswordTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("CooperativeAdmins");
                });

            modelBuilder.Entity("AjoCoreBackend.Domain.Entities.CooperativeGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CooperativeAdminId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CooperativeAdminId");

                    b.ToTable("CooperativeGroups");
                });

            modelBuilder.Entity("AjoCoreBackend.Domain.Entities.CooperativeGroupMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CooperativeGroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TraderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TraderId");

                    b.HasIndex("CooperativeGroupId", "TraderId")
                        .IsUnique();

                    b.ToTable("CooperativeGroupMembers");
                });

            modelBuilder.Entity("AjoCoreBackend.Domain.Entities.InboundTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TraderId")
                        .HasColumnType("uuid");

                    b.Property<string>("TransactionReference")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TraderId");

                    b.HasIndex("TransactionReference")
                        .IsUnique();

                    b.ToTable("InboundTransactions");
                });

            modelBuilder.Entity("AjoCoreBackend.Domain.Entities.NombaVirtualAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("BankName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("NombaVirtualAccounts");
                });

            modelBuilder.Entity("AjoCoreBackend.Domain.Entities.PayoutLedger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MerchantTxRef")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("PayoutDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SavingCycleMemberId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MerchantTxRef")
                        .IsUnique();

                    b.HasIndex("SavingCycleMemberId");

                    b.ToTable("PayoutLedgers");
                });

            modelBuilder.Entity("AjoCoreBackend.Domain.Entities.ReversalLedger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("OriginalWebhookRequestId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ReversalTxRef")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("SavingCycleMemberId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SavingCycleMemberId");

                    b.ToTable("ReversalLedgers");
                });

            modelBuilder.Entity("AjoCoreBackend.Domain.Entities.RotationalSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedMemberId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EstimatedPayoutDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAssigned")
                        .HasColumnType("boolean");

                    b.Property<Guid>("SavingCycleId")
                        .HasColumnType("uuid");

                    b.Property<int>("SlotNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignedMemberId");

                    b.HasIndex("SavingCycleId", "SlotNumber")
                        .IsUnique();

                    b.ToTable("RotationalSlots");
                });

            modelBuilder.Entity("AjoCoreBackend.Domain.Entities.SavingCycle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ContributionAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("CooperativeGroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CycleType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IntervalDays")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CooperativeGroupId");

                    b.ToTable("SavingCycles");
                });

            modelBuilder.Entity("AjoCoreBackend.Domain.Entities.SavingCycleMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("NombaVirtualAccountId")
                        .HasColumnType("uuid");

                    b.Property<int>("PayoutOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("SavingCycleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NombaVirtualAccountId")
                        .IsUnique();

                    b.HasIndex("SavingCycleId", "PayoutOrder")
                        .IsUnique();

                    b.ToTable("SavingCycleMembers");
                });

            modelBuilder.Entity("AjoCoreBackend.Domain.Entities.Trader", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bvn")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsKycCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayoutAccountName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("PayoutAccountNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PayoutBankName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResetPasswordToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ResetPasswordTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Traders");
                });

            modelBuilder.Entity("AjoCoreBackend.Domain.Entities.ContributionLedger", b =>
                {
                    b.HasOne("AjoCoreBackend.Domain.Entities.SavingCycleMember", "Member")
                        .WithMany("Contributions")
                        .HasForeignKey("SavingCycleMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("AjoCoreBackend.Domain.Entities.CooperativeGroup", b =>
                {
                    b.HasOne("AjoCoreBackend.Domain.Entities.CooperativeAdmin", "CooperativeAdmin")
                        .WithMany("AdministeredGroups")
                        .HasForeignKey("CooperativeAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CooperativeAdmin");
                });

            modelBuilder.Entity("AjoCoreBackend.Domain.Entities.CooperativeGroupMember", b =>
                {
                    b.HasOne("AjoCoreBackend.Domain.Entities.CooperativeGroup", "Group")
                        .WithMany("Members")
                        .HasForeignKey("CooperativeGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AjoCoreBackend.Domain.Entities.Trader", "Trader")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("TraderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Trader");
                });

            modelBuilder.Entity("AjoCoreBackend.Domain.Entities.InboundTransaction", b =>
                {
                    b.HasOne("AjoCoreBackend.Domain.Entities.Trader", "Trader")
                        .WithMany("Transactions")
                        .HasForeignKey("TraderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Trader");
                });

            modelBuilder.Entity("AjoCoreBackend.Domain.Entities.PayoutLedger", b =>
                {
                    b.HasOne("AjoCoreBackend.Domain.Entities.SavingCycleMember", "Member")
                        .WithMany("Payouts")
                        .HasForeignKey("SavingCycleMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("AjoCoreBackend.Domain.Entities.ReversalLedger", b =>
                {
                    b.HasOne("AjoCoreBackend.Domain.Entities.SavingCycleMember", "Member")
                        .WithMany()
                        .HasForeignKey("SavingCycleMemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("AjoCoreBackend.Domain.Entities.RotationalSlot", b =>
                {
                    b.HasOne("AjoCoreBackend.Domain.Entities.SavingCycleMember", "AssignedMember")
                        .WithMany()
                        .HasForeignKey("AssignedMemberId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AjoCoreBackend.Domain.Entities.SavingCycle", "Cycle")
                        .WithMany()
                        .HasForeignKey("SavingCycleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedMember");

                    b.Navigation("Cycle");
                });

            modelBuilder.Entity("AjoCoreBackend.Domain.Entities.SavingCycle", b =>
                {
                    b.HasOne("AjoCoreBackend.Domain.Entities.CooperativeGroup", "CooperativeGroup")
                        .WithMany("Cycles")
                        .HasForeignKey("CooperativeGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CooperativeGroup");
                });

            modelBuilder.Entity("AjoCoreBackend.Domain.Entities.SavingCycleMember", b =>
                {
                    b.HasOne("AjoCoreBackend.Domain.Entities.NombaVirtualAccount", "VirtualAccount")
                        .WithOne("Member")
                        .HasForeignKey("AjoCoreBackend.Domain.Entities.SavingCycleMember", "NombaVirtualAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AjoCoreBackend.Domain.Entities.SavingCycle", "Cycle")
                        .WithMany("Members")
                        .HasForeignKey("SavingCycleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cycle");

                    b.Navigation("VirtualAccount");
                });

            modelBuilder.Entity("AjoCoreBackend.Domain.Entities.CooperativeAdmin", b =>
                {
                    b.Navigation("AdministeredGroups");
                });

            modelBuilder.Entity("AjoCoreBackend.Domain.Entities.CooperativeGroup", b =>
                {
                    b.Navigation("Cycles");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("AjoCoreBackend.Domain.Entities.NombaVirtualAccount", b =>
                {
                    b.Navigation("Member");
                });

            modelBuilder.Entity("AjoCoreBackend.Domain.Entities.SavingCycle", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("AjoCoreBackend.Domain.Entities.SavingCycleMember", b =>
                {
                    b.Navigation("Contributions");

                    b.Navigation("Payouts");
                });

            modelBuilder.Entity("AjoCoreBackend.Domain.Entities.Trader", b =>
                {
                    b.Navigation("GroupMemberships");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
